title: "Hajar EL BERRAH"
description: "Data Scientist spécialisée en modélisation statistique, Machine Learning et R Shiny."
author: "Hajar EL BERRAH"

theme: minima

lang: fr
timezone: Europe/Paris

email: hajarelberrah0@gmail.com
github_username: ton-username
linkedin_username: ton-linkedin

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/ton-username" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ton-linkedin/" }
